### ISSUE TITLE
[question]: How did you compile esbuild with plugins support?

### ISSUE THREAD

**Issue by ImedAdel** [EMH333/esbuild-svelte#1]
I am trying to use this plugin and write some other ones but I can't figure out how to compile esbuild with plugins support. Could you give me a hint? :)

**Comment by EMH333** [comment]
To be honest I haven't gotten a full pipeline working yet. It sounds like Evan is still working on finalizing the plugin API so as that gets closer to being set I will try again. 

In theory you can just checkout the plugins branch, run `make platform-all` (or `make platform-<your_platform>`) then copy the binary from the npm folder of the esbuild repo to `esbuild/bin` in node_modules of the project you want plugin support for. It won't survive across `npm update`s (or maybe even installing new packages?) but should be a start.

**Comment by EMH333** [comment]
@ImedAdel I have updated the README with instructions and fixed an error that would have prevented you from running this plugin. Please give it a shot now!

**Comment by EMH333** [comment]
Closing this issue b/c of no response from OP
