### ISSUE TITLE
esbuild-svelte breaks watch mode on error

### ISSUE THREAD

**Issue by PierBover** [EMH333/esbuild-svelte#115]
**Describe the bug**
When `esbuild-svelte` encounters and error it seems to break the watch mode of esbuild.

After the error occurs, esbuild doesn't rebuild the file after it has been saved again.

This is my EsBuild config:

```
esbuild.build({
  entryPoints: ['index.js'],
  bundle: true,
  outdir: 'dist',
  plugins: [
    sveltePlugin({
      compilerOptions: {
        css: false,
        hydratable: true
      }
    })
  ],
  minify: false,
  incremental: true,
  watch: {
    onRebuild (error, result) {
      if (error) console.error('SVELTE watch build failed:', error);
    }
  },
  logLevel
}).catch((error) => {
  console.log(error);
});
```
**To Reproduce**

1. Create a Svelte file with an error

```
<script>
	import Something
</script>

<div>Hello</div>
```

2. The plugin will produce this error:
```
✘ [ERROR] [plugin esbuild-svelte] Unexpected token
```

3. After correcting the file and saving, watch mode will not rebuild.

**Expected behavior**

After the plugin reports and error, and the error is corrected, EsBuild should rebuild again but it doesn't.

**Environment (please complete the following information):**

- esbuild-svelte version: ^0.6.3
- esbuild version: ^0.14.23

**Comment by Prinzhorn** [comment]
Can you provide _full_ steps to reproduce? I created a build.js with the following adjusted contents:

```js
const esbuild = require('esbuild');
const sveltePlugin = require('esbuild-svelte');

esbuild.build({
  entryPoints: ['index.js'],
  bundle: true,
  outdir: 'dist',
  plugins: [
    sveltePlugin({
      compilerOptions: {
        css: false,
        hydratable: true
      }
    })
  ],
  minify: false,
  incremental: true,
  watch: {
    onRebuild (error, result) {
      if (error) console.error('SVELTE watch build failed:', error);
    }
  },
}).catch((error) => {
  console.log(error);
});
```

And index.js

```js
import App from './App.svelte';

new App(document.body);
```

And I cannot reproduce it. When I uncomment the broken import it will rebuild. I confirmed that by deleting `dist/index.js` and see it appear after saving.

**Comment by PierBover** [comment]
Hmmm you're right.

I created this repro and it rebuilds fine.

https://github.com/PierBover/esbuild-svelte-error-repro

The issue must be somewhere else. Sorry to waste your time!
