### ISSUE TITLE
Make Svelte a peer dependency

### ISSUE THREAD

**Issue by Prinzhorn** [EMH333/esbuild-svelte#117]
**Is your feature request related to a problem? Please describe.**

I didn't realize the Svelte version is tied to `esbuild-svelte`. I was looking through the release notes and noticed that Svelte upgrades were part of them. There's no reason that this package needs to push an update just for people to receive Svelte fixes. This means people are either locked into an outdated Svelte version or into a newer one that introduced a breaking bug.

**Describe the solution you'd like**

Make Svelte a peer dependency

Rollup has peer: https://github.com/sveltejs/rollup-plugin-svelte/blob/8bc5ee49fec60ce32ee2cf9f285461348bece75c/package.json#L32
Webpack has peer: https://github.com/sveltejs/svelte-loader/blob/5e7853f233d7be5592b0b5fc22da9b4d1a5b0c12/package.json#L32
Vite doesn't list it at all, only as dev: https://github.com/sveltejs/vite-plugin-svelte/blob/1f7834494621cdecffac27539a9246387f6eb710/package.json
Parcel doesn't list it at all but the install instructions contain the Svelte package: https://github.com/DeMoorJasper/parcel-plugin-svelte/blob/7733036ee1a5747da46a8155b35b24bf23914793/package.json

I'd put the minimum version to one that has the required API for esbuild-svelte to work.

**Describe alternatives you've considered**

I think if I have the latest Svelte in my dependencies then this also matches what esbuild-svelte needs, so it's technically not necessary to update esbuild-svelte to get the latest Svelte.

**Comment by EMH333** [comment]
Completely agree, I started with it as a dependency and haven't bothered to change it. Thanks for creating a tracking issue!

**Comment by EMH333** [comment]
Released as `v0.7.0`
