### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by winston0410** [EMH333/esbuild-svelte#122]
**Describe the bug**

```
 > src/MetaData.svelte:2:17: error: [plugin: esbuild-svelte] Unexpected token
    2 │ 1: <script lang="ts">
      ╵                  ^
2:   export let title: string, description: string, image: string, url: string;
                     ^
3: </script>
4:

   src/index.ts:1:26: note: The plugin "esbuild-svelte" was triggered by this import
    1 │ export * as MetaData from './MetaData.svelte'
      ╵                           ~~~~~~~~~~~~~~~~~~~
```

**To Reproduce**

The file that causes the error:

```svelte
<script lang="ts">
	export let title: string, description: string, image: string, url: string;
</script>
```

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**

- esbuild-svelte version: 0.6.3
- esbuild version: 0.12.24
- Svelte preprocessors used (if any):

**Additional context**

**Comment by Prinzhorn** [comment]
> **To Reproduce**

Can you post full steps to reproduce, including package.json and your esbuild `build.js` script? I'm sure you've added the required setup for Typescript? https://github.com/EMH333/esbuild-svelte#typescript-and-other-svelte-preprocessing

**Comment by EMH333** [comment]
I'm going to close this because I suspect you haven't set up typescript integration and it's been 3+months since an update. Feel free to respond if an issue persists and you have more details to share
