### ISSUE TITLE
Breaks watch mode on error when preprocess dependency transformation fails

### ISSUE THREAD

**Issue by maxiruani** [EMH333/esbuild-svelte#131]
**Describe the bug**
If preprocess fails execution of a dependency (eg: an external `scss` file imported within a `<style>` tag).
The `onLoad` returning `watchFiles` are lost and editing the external `scss` does not trigger the rebuild.

**To Reproduce**

1. Create a `.svelte` file with a `<style lang="scss">`  with an external import `@import "./external-file.scss";` with valid syntax.
2. Start watch mode.
3. Edit `external-file.scss` with some invalid syntax.
4. Rebuild is triggered and fails.
5. Edit `external-file.scss` with valid syntax.
6. Rebuild is *not* triggered.

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**

- esbuild-svelte version: `0.7.0`
- esbuild version: `0.14.42`
- Svelte preprocessors used (if any): `SCSS`

**Comment by EMH333** [comment]
Good catch! Thanks for the clear report.

I'm a bit backed up at the moment, but I'll do my best to get this fixed soon!

**Comment by maxiruani** [comment]
Checking the code I thought in a solution to keep the previous build `watchFiles` based on the "invalidated" `cachedFile.dependencies`.
Due to `preprocess` nature we can't get the resolved dependencies by `svelte-preprocess`.

Another caveat I found is that if the external scss file has invalid syntax from the start, esbuild watch fails and exit the process, but I don't figure it out how to fix that.

Let me know if you like this solution and I can try to implement it.

Thanks!

**Comment by EMH333** [comment]
You are welcome to give it a shot!

**Comment by maxiruani** [comment]
I have created a PR ( #132 ). Let me know what you think!
Thanks

**Comment by EMH333** [comment]
Released as a part of `v0.7.1`. Thanks for the contribution!
