### ISSUE TITLE
svelte: 3.53.0 ▲ [WARNING] [plugin esbuild-svelte] options.css as a boolean is deprecated. Use 'external' instead of false.

### ISSUE THREAD

**Issue by usrtax** [EMH333/esbuild-svelte#150]
svelte: 3.53.0 ▲ [WARNING] [plugin esbuild-svelte] options.css as a boolean is deprecated. Use 'external' instead of false.

https://github.com/sveltejs/svelte/pull/7914

**Comment by EMH333** [comment]
Yep! Looks like they finally released the new version (see prior work here https://github.com/EMH333/esbuild-svelte/pull/109). Svelte `v3.53.1` removed the deprecation warnings for now, so there is a bit of time. I'll get a new esbuild-svelte version released sometime next week

**Comment by EMH333** [comment]
Released as `v0.7.2`
