### ISSUE TITLE
Can’t run example as is

### ISSUE THREAD

**Issue by aral** [EMH333/esbuild-svelte#16]
When I try to load in the generated files in the example using a basic HTML wrapper like the one below, I’m getting an empty HTML page (the script and styles load but nothing is rendered):

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Test</title>
  <link rel="stylesheet" href="./entry.css">
</head>
<body>
  <script type="module" src="./entry.js"></script>
</body>
</html>
```

If I replace `binding: document.body` with `target: document.body` in entry.js, the app shows up. So, the following entry.js works insofar as the app displaying in the browser:

```js
import Test from './index.svelte';

new Test({
  target: document.body,
});
```

However, if you click the button, you get the following error:

```js
Uncaught TypeError: lol is undefined
  change https://localhost/entry.js:448
  listen https://localhost/entry.js:56
  m https://localhost/entry.js:411
  mount_component https://localhost/entry.js:194
  init https://localhost/entry.js:268
  Index https://localhost/entry.js:455
  <anonymous> https://localhost/entry.js:462
```

**Comment by aral** [comment]
PS. My URLs are showing https://localhost as I’m running it using Site.js (https://sitejs.org). I get the same results with a simple `python3 -m http.server`.

**Comment by EMH333** [comment]
yep, that's my fault for not focusing on the example for anything more than smoke testing :/

As of daccc90c9ceda4610abd5281e8a27db3e5464641, I have updated the example so it actually works correctly in the browser. Nothing changed in the actual plugin, just the example code

Hopefully it will be more helpful now, thanks for bringing it to my attention!

**Comment by aral** [comment]
Thanks :)
