### ISSUE TITLE
Option to enable svelte-check?

### ISSUE THREAD

**Issue by NfNitLoop** [EMH333/esbuild-svelte#160]
I just realized that esbuild-svelte doesn't do type checks, because svelte preprocessor [doesn't do type checks][1]. 

[1]: https://github.com/sveltejs/svelte-preprocess/blob/main/docs/preprocessing.md#typescript---limitations

I'd love to (optionally) include type checks in my esbuild run because they can save me a lot of runtime headaches. 

It would be nice if this were an option in esbuild-svelte so I don't have to roll my own.

I suppose as a workaround I can hack it into my package.json scripts to just run before kicking off esbuild.

**Comment by EMH333** [comment]
Unfortunately I think the "hack" of adding svelte-check or something similar into your npm scripts is probably the best bet here.

[esbuild doesn't do type checks](https://esbuild.github.io/content-types/#typescript) either, which means there isn't really a clean way for `esbuild-svelte` to incorporate type checks into it's run without adding extraneous dependencies for non-typescript users.

Open to suggestions on this, but I see type checks as the responsibility of an external program (like `svelte-check`) or a preprocessor.

**Comment by EMH333** [comment]
Closing this as out of scope
