### ISSUE TITLE
Unexpected token error with latest svelte-preprocess v5

### ISSUE THREAD

**Issue by ginpei** [EMH333/esbuild-svelte#178]
**Describe the bug**
esbuild-svelte started throwing errors after upgrading svelte-preprocess and TypeScript (I upgraded both for peer deps conflict)

```
$ node build.js 
✘ [ERROR] Unexpected token [plugin esbuild-svelte]

    MyComponent.svelte:2:13:
      2 │ 1: <script type="typescript">
        ╵              ^

2:   import type { Foo } from './foo';
                 ^
3: 
4:   const foo: Foo = 'bar';

  The plugin "esbuild-svelte" was triggered by this import

    index.ts:1:24:
      1 │ import MyComponent from './MyComponent.svelte';
        ╵                         ~~~~~~~~~~~~~~~~~~~~~~
```

**To Reproduce**

Run the build script where the followings are installed

`package.json`

```json
{
  "private": true,
  "dependencies": {
    "esbuild": "^0.17.16",
    "esbuild-svelte": "^0.7.3",
    "svelte": "^3.58.0",
    "svelte-preprocess": "^5.0.3",
    "typescript": "^5.0.4"
  }
}
```

(I confirmed the lock file tells the save versions.)

`build.js`

```js
const esbuild = require('esbuild');
const esbuildSvelte = require('esbuild-svelte');
const path = require('path');
const sveltePreprocess = require('svelte-preprocess');

esbuild
  .build({
    entryPoints: [path.resolve(__dirname, './index.ts')],
    mainFields: ['svelte', 'browser', 'module', 'main'],
    bundle: true,
    outdir: path.resolve(__dirname, './dist'),
    plugins: [
      esbuildSvelte({
        preprocess: sveltePreprocess(),
      }),
    ],
  })
  .catch(() => process.exit(1));
```

`MyComponent.svelte`

```svelte
<script type="typescript">
  import type { Foo } from './foo';
…
```

**Expected behavior**

Compile them as well as recent versions

**Screenshots**

N/A

**Environment (please complete the following information):**

- esbuild-svelte version: 0.7.3
- esbuild version: 0.17.16
- Svelte preprocessors used (if any): 5.0.3

**Additional context**

- It works with previous versions: svelte-preprocess v4.10.7 and TypeScript v4.9.5
- Importing values works. Only `type` seems problematic
- Tried on Node.js v16.19.1, v18.15.0

**Comment by EMH333** [comment]
Please note the [`svelte-preprocess` release notes](https://github.com/sveltejs/svelte-preprocess/blob/main/CHANGELOG.md#breaking-changes) for version `5.0.0`. The most relevant change is:

> Cannot use "type" attribute to identify the language of a style or script tag anymore. Use lang instead

**Comment by ginpei** [comment]
Perfect. Thank you!

```diff
-<script type="typescript">
+<script lang="typescript">
```
