### ISSUE TITLE
svelte@4 - compilerOptions.css as a boolean is deprecated

### ISSUE THREAD

**Issue by Valexr** [EMH333/esbuild-svelte#185]
**Describe the bug**
compilerOptions.css as a boolean is deprecated. Use 'external' instead of false.

**To Reproduce**
Any compilations

**Expected behavior**
Use 'external' instead of false.

- esbuild-svelte version: latest
- esbuild version: latet
- Svelte preprocessors used (if any): yes

**Comment by EMH333** [comment]
Svelte v4 support hasn't been verified yet for esbuild-svelte (I should have tightened the version locks). Thanks for the report and I should have it resolved later this week!

**Comment by Valexr** [comment]
So far, it's just a warning. Maybe later will be as deprecated error…

**Comment by EMH333** [comment]
Fixed in `esbuild-svelte@0.7.4`
