### ISSUE TITLE
customElement option throws an error

### ISSUE THREAD

**Issue by Jeggle-s** [EMH333/esbuild-svelte#189]
**Describe the bug**
Today I upgraded esbuild-svelte to version 0.74 with Svelte 4 as dependency. In the migration guide it states, that the Tag-Option for custom components is deprecated with Svelte 4 and was replaced with the customElement option (see https://svelte.dev/docs/v4-migration-guide#custom-elements-with-svelte). Using this new option, the esbuild-svelte plugin throws following error:

`<svelte:options> unknown attribute`

**To Reproduce**

1. Define a custom component tag with <svelte:options customElement="my-component">
2. Include this component in an HTML file
3. See error

**Expected behavior**
No error should be thrown. The error should only occur if the old option (tag) was used.

**Environment:**

- esbuild-svelte version: 0.7.4
- esbuild version: 0.17.5
- Svelte preprocessors used (if any): svelte-preprocess - 5.0.3

**Comment by EMH333** [comment]
I am unable to reproduce this issue when using Svelte 4. Are you sure you have upgraded to Svelte 4 (`npm install svelte@4`)?

**Comment by Jeggle-s** [comment]
Ah damn it. I did not update all my dependencies. Error was in front of the monitor. I'm closing this issue.
