### ISSUE TITLE
FEATURE: caching unmodified files

### ISSUE THREAD

**Issue by apairon** [EMH333/esbuild-svelte#19]
It would be nice to see a caching feature in this plugin. I use this plugin with esbuild + filewatcher and modified your plugin with a few lines for my needs.

```javascript
...
const fileCache = {}
...
            //main loader
            build.onLoad({ filter: /\.svelte$/ }, async (args) => {

                const cached = fileCache[args.path]
                if (cached && fs.statSync(args.path).mtime < cached.time) {
                    return cached.data
                }

...

                    fileCache[args.path] = {
                        time: new Date(),
                        data: { contents, warnings: warnings.map(convertMessage) }
                    }

                    console.log(args.path + " compiled")
                    return fileCache[args.path].data
                } catch (e) {
                    return { errors: [convertMessage(e)] }
                }
...
```

This modification was made to version 0.3.1. I hope to see such a caching feature in your plugin in a future version, so that I do not have to use my modified version.

Thank you

**Comment by EMH333** [comment]
Hmm! This probably would be very helpful for long living esbuild services, however it would have little to no impact on a one-and-done workflow, like running a single build. I will likely end up putting this behind a config flag so it won't affect existing workflows that don't require this (something like `cache: true` if it should use a file cache, defaulting to `false`).

Thanks for the feature request, you are welcome to convert your modifications into a PR or I will get around to it in the next week or so

**Comment by EMH333** [comment]
FYI, support for a `cache` option has been pushed to the `main` branch. I'm going to wait till I'm less tired to cut a release to make sure I don't miss anything, but know this is coming your way soon

**Comment by EMH333** [comment]
Support for a `cache` option has been added in `v0.4.1`
