### ISSUE TITLE
Migrate error and warning codes for Svelte 5 support (including in tests)

### ISSUE THREAD

**Issue by Greenheart** [EMH333/esbuild-svelte#232]
**Describe the bug**

This is related my comment in #230 about finding out that we likely need to upgrade the compiler + tests to svelte 5. It's good to know that the error + warning codes have changed the separator from `-` to `_`.

More details:
https://svelte-5-preview.vercel.app/docs/breaking-changes#other-breaking-changes-error-warning-codes-have-been-renamed

**Comment by Greenheart** [comment]
The warning `missing-declaration` seems to have been removed in Svelte 5

For Svelte 5, searching for `missing` in this page, there is no match: https://github.com/sveltejs/svelte/blob/main/packages/svelte/src/compiler/warnings.js

For Svelte 4, the warning still exists
https://github.com/sveltejs/svelte/blob/d04c146b4649e47d4cb86a93cfa33b910a229591/packages/svelte/src/compiler/compile/compiler_warnings.js#L30

This probably means we need to update the test case checking for this removed compiler warning, and instead trigger another warning. Then we can preserve the intention of the test, but not rely on the changed compiler output in Svelte 5.

**Comment by EMH333** [comment]
This has been fixed for [v0.9.0](https://github.com/EMH333/esbuild-svelte/releases/tag/v0.9.0)

(Thank you for your earlier PR, it wasn't merged but was a very helpful reference for a few things!)

**Comment by Greenheart** [comment]
Thanks for fixing this! No worries, most important is to improve the project and move it forward :smile:

Keep up the good work!
