### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by HalfdanJ** [EMH333/esbuild-svelte#25]
Does the plugin support typescript based svelte files? I tried running it, but getting errors with typescript syntax, and I'm unsure if I can configure the plugin to support it.

**Comment by EMH333** [comment]
You will need to include `svelte-preprocess` as a preprocessor. A simple code example is shown below:

```javascript
const sveltePreprocess = require('svelte-preprocess');
const esbuildSvelte = require('esbuild-svelte');
const esbuild = require('esbuild');

esbuild.build({
  entryPoints: ['index.js'],
  bundle: true,
  outdir: './dist',
  plugins: [esbuildSvelte({
    preprocessor: sveltePreprocess()
  })],
}).catch(() => process.exit(1));
```

Right now this unfortunately does break sourcemaps if you use them but I am working to fix that.


I also should probably make this process more obvious in the README :)

**Comment by HalfdanJ** [comment]
Perfect, thank you!

**Comment by EMH333** [comment]
Additional documentation for using `svelte-preprocess` and other preprocessors has been added to the README
