### ISSUE TITLE
Svelte 5: compileModule

### ISSUE THREAD

**Issue by yolk** [EMH333/esbuild-svelte#250]
esbuild-svelte ignores *.svelte.js and *.svelte.ts files containing runes from svelte 5.

To compile them, we would need to:

1. Alter the default value of the `include` option (something like `/\.svelte(\.ts|\.js)?$/`)
2. Detect module files before compilation and instead of calling the `compile` function call `compileModule` from 'svelte/compiler'. 

This would solve the problem for 'svelte.js' files, but not for 'svelte.ts', because sveltePreprocess only compiles svelte components. Maybe we could compile/preprocess them with esbuild before calling compileModule?

Thx!

**Comment by EMH333** [comment]
This is interesting, thank you for bringing this to my attention.

I agree with your prognosis, supporting `*.svelte.js` files will be straightforward. Supporting TS svelte modules will be less straightforward, however using esbuild to transform TS into JS seems like the best path.

**Comment by woutdp** [comment]
Super excited for this! Since you mentioned TS modules might be tricky, consider supporting `.svelte.js` without `.svelte.ts` for a first iteration as that would allow some usage of `esbuild-svelte` with Svelte 5.

**Comment by EMH333** [comment]
Support has been released in [v0.9.0](https://github.com/EMH333/esbuild-svelte/releases/tag/v0.9.0)
