### ISSUE TITLE
Can't build multi file project

### ISSUE THREAD

**Issue by alexanderniebuhr** [EMH333/esbuild-svelte#27]
I do get errors with imports and multiple svelte files. You have that in your example, what am I missing, do I need to have some special config? 

```zsh
 > src/App.svelte: error: Could not resolve "./Tailwindcss.svelte"
    14 │ import Tailwindcss from "./Tailwindcss.svelte";
```

**Comment by EMH333** [comment]
You shouldn't need any special config. I'm assuming the `Tailwindcss.svelte` file is also in your `src` directory?

**Comment by alexanderniebuhr** [comment]
Yes, it is. One file works perfectly fine, however multiple files seems to be an issue with me. I do not know my issue, might overlook something

```
| src
|-- App.svelte
|-- Tailwindcss.svelte
|-- index.js
| esbuild.js
| package.json
| svelte.config.js
| tailwind.config.js
```

index.js
```js
import App from "./App.svelte";

new App({
  target: document.body,
});
```

App.svelte
```svelte
<script>
  import Tailwind from './Tailwindcss.svelte'
  let name = 'world';
</script>

<div>
  <h1>Hello {name}!</h1>
</div>
```
Tailwindcss.svelte
```svelte
<style global>
  @tailwind base;
  @tailwind components;
  @tailwind utilities;
</style>
```

**Comment by EMH333** [comment]
Interesting! Are you using any additional esbuild plugins?

**Comment by alexanderniebuhr** [comment]
No I don't use any additional plugins, just svelte-preprocessor. I will have a look into it again, and try some naming convention stuff later today

**Comment by alexanderniebuhr** [comment]
Seems to work if I rename the file to `Tailwind.svelte`
However, I think it might be an issue with some extensions interfering. (sounds odd, but i guess this as the file resolve in vscode seems to be broken sometimes, like go to definition) Haven't found out which.

**Comment by alexanderniebuhr** [comment]
Still just works with filename `Tailwind.svelte`, does not work with `Tailwindcss.svelte`

I am fine with renaming it, however it seems not good that it is picky about filenames. However I can't make sure it isn't some other rules in my environment

**Comment by EMH333** [comment]
It's been close to two months now, if you have any new details or leads we can keep this open but I think it makes sense to close this issue considering there isn't anything in esbuild-svelte that should cause that behavior.

Thanks!
