### ISSUE TITLE
Can't load fake-css on esbuild over 0.5.1 

### ISSUE THREAD

**Issue by AlexxNB** [EMH333/esbuild-svelte#33]
Thanks for your work.
After update on esbuild@0.5.1 now get an error:
![изображение](https://user-images.githubusercontent.com/10389013/108949212-0dd13e00-7675-11eb-9622-00373efaa100.png)
Previous version of esbuild works great.

**Comment by AlexxNB** [comment]
The solution I found is to set namespace not equal `file` in `onResolve` method:
![изображение](https://user-images.githubusercontent.com/10389013/108951211-a1f0d480-7678-11eb-891e-69150bcc2d51.png)

**Comment by Valexr** [comment]
This update https://github.com/evanw/esbuild/blob/master/CHANGELOG.md#0851 – Change the import resolution rules of absolute paths (#862)

**Comment by alexanderniebuhr** [comment]
`bundle: false` works as a workaround
