### ISSUE TITLE
Don't resolve fakecss path with splitting: true options

### ISSUE THREAD

**Issue by Valexr** [EMH333/esbuild-svelte#39]
With splitting: true option don't load css chunks on the page...
Fakecss-path resolve when it's single bundle, but don't resolve with multiple chunks...

**Comment by EMH333** [comment]
I think this might be a known issue with esbuild and not necessarily this plugin. CSS code chunks are a work in progress feature (see https://github.com/evanw/esbuild/issues/608). Please correct me if I misunderstood!

**Comment by Valexr** [comment]
Seems like this... esbuild make splitting chunks css/js but haven't loader for css in html...

**Comment by EMH333** [comment]
Alright, I will close this then as it isn't a direct problem of esbuild-svelte. Once esbuild supports CSS code splitting, I will take another look and determine if I need to do anything on my end. Thanks for the report!
