### ISSUE TITLE
0.12.19 added CSS sourcemap

### ISSUE THREAD

**Issue by Valexr** [EMH333/esbuild-svelte#63]
Just for yours attention... maybe it's will be useful

https://github.com/evanw/esbuild/releases/tag/v0.12.19

![Screenshot 2021-08-08 at 12 20 10](https://user-images.githubusercontent.com/5656366/128627254-ccffc7d2-4cdf-47ce-ab2f-0d1eb781d2e6.jpg)

**Comment by EMH333** [comment]
Ah yes, let me look into that. Thanks for the report!

**Comment by EMH333** [comment]
Fixed in `v0.5.4`! Thanks again for the prompt report!
