### ISSUE TITLE
ENOENT error with latest version

### ISSUE THREAD

**Issue by varbhat** [EMH333/esbuild-svelte#71]
Hello , I was using esbuild-svelte for my Svelte Application(svelte+typescript+tailwindcss) and so far all good. But,when I updated svelte-preprocess to latest version , it will not build .

![image](https://user-images.githubusercontent.com/68165364/133640494-21bed3e3-4525-4e24-9889-0cfbf21cd168.png)

Steps to reproduce:
* Here , in this directory https://github.com/varbhat/exatorrent/tree/main/internal/web , if i execute `npm i && npm run build` , it will build successfully.
* Try updating svelte-preprocess
* Try building using `npm run build` . It throws error. 

@EMH333 , Please resolve this issue as soon as possible . Thank you for esbuild-svelte.

**Comment by EMH333** [comment]
Looks like it's something to do with `svelte-preprocess`'s new transpilation strategy for TypeScript introduced in `v4.9.0`. I'm not entirely sure where the trouble is given that one of my projects using a similar set up works just fine with `svelte-preprocess v4.9.4` and a bit of digging on my end doesn't seem to reveal anything helpful. I'll keep looking though. 

I see you have opened an issue with them, hopefully they have more insight. For now, you can disable the new strategy by adding `typescript: { handleMixedImports: false },` to the svelte-preprocess options in `esbuild.config.js`, while we work to solve this!

**Comment by EMH333** [comment]
scratch that, see https://github.com/sveltejs/svelte-preprocess/issues/405

**Comment by EMH333** [comment]
Closing as this isn't an issue with `esbuild-svelte`

**Comment by varbhat** [comment]
@EMH333 , Thank you very much
