### ISSUE TITLE
Proper CSS Code splitting

### ISSUE THREAD

**Issue by PuruVJ** [EMH333/esbuild-svelte#74]
**Is your feature request related to a problem? Please describe.**
This plugin code splits everything really well, but it is a bit weird at code splitting CSS. It generates a separate .css file for the code-splitted component, but inlines its styles right into the main index.css too. The other file is never loaded, and index.css does all the work.

I'm not sure whether this is a missing feature or a bug, but it seems like the generated code splitted .js file doesn't load its .css file, so maybe it's a missing feature.

**Describe the solution you'd like**
CSS should be code splitted well, and the splitted .css files be loaded when the respective splitted .js is loaded

**Describe alternatives you've considered**
Going with the flow here for now

And hey, love this plugin, it's saved so much time and amazing to integrate with ESBuild. Keep up the great work!

**Comment by EMH333** [comment]
I'll look into this but I believe this is a limitation of `esbuild` css handling, which doesn't code split css right now. Additionally, I'm hesitant to include code to import css as it can be incredibly fragile and would rather have that be a per-project configuration. We'll keep this open for tracking interest/updates.

Thanks for the report!

**Comment by EMH333** [comment]
I'm going to close this issue for now until more support for CSS splitting is baked into esbuild
